CREATE TABLE manobo_leads (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lead_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    comment TEXT,
    date_added TIMESTAMPTZ DEFAULT now() NOT NULL
);